# Generated by Django 2.2.3 on 2022-08-29 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentario',
            new_name='Comentario',
        ),
    ]
