# Generated by Django 2.2.3 on 2022-08-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreYapellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('pais', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='noticias')),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='home')),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Descargas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='descargas')),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='CursosYCapacitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='cursosYcapacitaciones')),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombreYapellido', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('ciudad', models.CharField(max_length=20)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='aplicaciones')),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_socio', models.BooleanField()),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectoccvaapp.Usuario')),
            ],
        ),
    ]
