# Generated by Django 2.2.3 on 2022-08-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoccvaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosycapacitaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cursosycapacitaciones'),
        ),
    ]
